"""Sonny's Carwash Controls Data API client."""

from sonnys_data_client._client import SonnysClient
from sonnys_data_client._version import __version__
from sonnys_data_client.resources import (
    BackOfficeResource,
    Customers,
    Employees,
    Giftcards,
    Items,
    RecurringAccounts,
    Sites,
    StatsResource,
    Transactions,
    Washbooks,
)

from sonnys_data_client.types import (
    BackOfficeTimeclockResult,
    ConversionResult,
    CostPerCarResult,
    EmployeeTimesheet,
    LaborCostResult,
    SalesResult,
    StatsReport,
    TimesheetShift,
    WashResult,
)

from sonnys_data_client._exceptions import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    AuthError,
    BackOfficeCredentialsError,
    BackOfficeError,
    BackOfficeLoginError,
    BackOfficeScrapeError,
    NotFoundError,
    RateLimitError,
    ServerError,
    SonnysError,
    ValidationError,
)

__all__ = [
    "SonnysClient",
    "__version__",
    "BackOfficeResource",
    "Customers",
    "Employees",
    "Giftcards",
    "Items",
    "RecurringAccounts",
    "BackOfficeTimeclockResult",
    "ConversionResult",
    "CostPerCarResult",
    "EmployeeTimesheet",
    "LaborCostResult",
    "SalesResult",
    "Sites",
    "TimesheetShift",
    "WashResult",
    "StatsReport",
    "StatsResource",
    "Transactions",
    "Washbooks",
    "APIConnectionError",
    "APIError",
    "APIStatusError",
    "APITimeoutError",
    "AuthError",
    "BackOfficeCredentialsError",
    "BackOfficeError",
    "BackOfficeLoginError",
    "BackOfficeScrapeError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "SonnysError",
    "ValidationError",
]
